---
services:
  solr:
    networks:
      - freva-rest
    image: ghcr.io/freva-org/freva-solr:latest
    ports:
      - "8983:8983"
    hostname: solr

  mongodb:
    networks:
      - freva-rest
    image: ghcr.io/freva-org/freva-mongo:latest
    environment:
      API_MONGO_DB: metadata
      API_MONGO_USER: mongo
      API_MONGO_PASSWORD: secret
    hostname: mongodb
    ports:
      - "27017:27017"


networks:
  freva-rest:
    driver: bridge
